filepath:
  src: "src/main/resources/filtered-tradeName-"
urls:
  exceptionservice: ${env.EXCEPTION_SERVICE_URL:http://localhost:8069/}
  transformservice: ${env.TRANSFORM_DATA_SERVICE_URL:http://localhost:8085/}